version: "3.9"
services:
  app2-1:
    image: app2
    container_name: app2-1
    networks:
      appnet:
        ipv4_address: 172.20.0.100
    depends_on:
      - mysql


  app2-2:
    image: app2
    container_name: app2-2
    networks:
      appnet:
        ipv4_address: 172.20.0.101
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      appnet:
        ipv4_address: 172.20.0.200
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ~/DOCKER/DB2:/var/lib/mysql 
    ports:
      - "3306:3306"

  lb2:
    image: lb2
    container_name: lb2
    networks:
      appnet:
        ipv4_address: 172.20.0.10
    ports:
      - "9280:8080"
    depends_on:
      - app2-1
      - app2-2
    command: ["nginx", "-g", "daemon off;"]

networks:
  appnet:
    external: true
      